"""add habit persistence models

Revision ID: d754cbbf0c2a
Revises: 301f6fae92a7
Create Date: 2026-10-04 10:39:19.456270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd754cbbf0c2a'
down_revision: Union[str, Sequence[str], None] = '301f6fae92a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'FORMED', 'EXPIRED', name='habit_status'), nullable=False),
    sa.Column('allow_backfill', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_habits_end_date_not_before_start_date'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_id'), 'habits', ['id'], unique=False)
    op.create_index(op.f('ix_habits_owner_id'), 'habits', ['owner_id'], unique=False)
    op.create_table('habit_check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('tracked_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DONE', 'NOT_DONE', name='habit_check_in_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'tracked_date', name='uq_habit_check_ins_habit_tracked_date')
    )
    op.create_index(op.f('ix_habit_check_ins_habit_id'), 'habit_check_ins', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_check_ins_id'), 'habit_check_ins', ['id'], unique=False)
    op.create_table('habit_schedule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('daily_target_minutes', sa.Integer(), nullable=True),
    sa.CheckConstraint('daily_target_minutes IS NULL OR daily_target_minutes > 0', name='ck_habit_schedule_versions_daily_target_positive'),
    sa.CheckConstraint('monday OR tuesday OR wednesday OR thursday OR friday OR saturday OR sunday', name='ck_habit_schedule_versions_at_least_one_weekday'),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'effective_from', name='uq_habit_schedule_versions_habit_effective_from')
    )
    op.create_index(op.f('ix_habit_schedule_versions_habit_id'), 'habit_schedule_versions', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_schedule_versions_id'), 'habit_schedule_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_habit_schedule_versions_id'), table_name='habit_schedule_versions')
    op.drop_index(op.f('ix_habit_schedule_versions_habit_id'), table_name='habit_schedule_versions')
    op.drop_table('habit_schedule_versions')
    op.drop_index(op.f('ix_habit_check_ins_id'), table_name='habit_check_ins')
    op.drop_index(op.f('ix_habit_check_ins_habit_id'), table_name='habit_check_ins')
    op.drop_table('habit_check_ins')
    op.drop_index(op.f('ix_habits_owner_id'), table_name='habits')
    op.drop_index(op.f('ix_habits_id'), table_name='habits')
    op.drop_table('habits')

    sa.Enum(
        'DONE',
        'NOT_DONE',
        name='habit_check_in_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        'ACTIVE',
        'FORMED',
        'EXPIRED',
        name='habit_status',
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
