name: CI Pipeline

on:
  push:
    branches:
        - main

jobs:
  test-our-code:
    runs-on: ubuntu-latest

    steps:
      - name: Upload code on server
        uses: actions/checkout@v4
      
      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installing libraries
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      
      - name: Deploy tests
        run: |
          python -m pytest
  build-and-push:
    needs: test-our-code
    runs-on: ubuntu-latest

    steps:
      - name: Uploading code
        uses: actions/checkout@v4

      - name: Log in DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Deploying
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/observerapp:latest